demo-store/config/routes.rb
MpowerNew::Application.routes.draw do
  resources :carts
  match "cart/checkout" => "carts#checkout", :as => :checkout
  match "cart/request_charge" => "carts#request_charge", :as => :request_charge
  match "cart/perform_charge" => "carts#perform_charge", :as => :perform_charge
  match "cart/confirmation" => "carts#confirmation", :as => :confirmation

  root :to => 'carts#index'

end

demo-store/app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :price, :product_name, :quantity

  def total_price
  	quantity*price
  end
end

demo-store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

demo-store/app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def checkout
    # We will programatically simulate the last 6 cart items as checkout items
    @items = Cart.order("created_at DESC").limit(6)
    co = MPower::Checkout::Invoice.new
    total_amount = 0.0
    @items.each do | item |
      co.add_item(item.product_name,item.quantity,item.price,item.total_price)
      total_amount += item.total_price
    end
    co.total_amount = total_amount
    if co.create
        redirect_to co.invoice_url
    else
        redirect_to root_url, :notice => co.response_text
    end
  end

  def request_charge
    # We will programatically simulate the last 6 cart items as checkout items
    @items = Cart.order("created_at DESC").limit(6)
    co = MPower::Onsite::Invoice.new
    total_amount = 0.0
    @items.each do | item |
      co.add_item(item.product_name,item.quantity,item.price,item.total_price)
      total_amount += item.total_price
    end
    co.total_amount = total_amount
    if co.create(params[:checkout][:account_alias])
      @token = co.token
    else
      redirect_to root_url, :notice => co.response_text
    end
  end

  def perform_charge
    co = MPower::Onsite::Invoice.new
    if co.charge(params[:checkout][:opr_token],params[:checkout][:confirm_token])
      @receipt_url = co.receipt_url
      @message = co.response_text
      @customer_name = co.customer["name"]
    else
      redirect_to root_url, :notice => co.response_text
    end
  end

  def confirmation
    co = MPower::Checkout::Invoice.new
    co.confirm(params[:token])
    @result = co
  end

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end
end

demo-store/app/helpers/application_helper.rb
module ApplicationHelper
end

demo-store/app/helpers/carts_helper.rb
module CartsHelper
end

demo-store/app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_name %><br />
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

demo-store/app/views/carts/confirmation.html.erb
<%= @result.inspect %>

demo-store/app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

demo-store/app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing carts</h1>

<table>
  <tr>
    <th>Product name</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>Total Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= cart.product_name %></td>
    <td><%= cart.quantity %></td>
    <td><%= cart.price %></td>
    <td><%= cart.total_price %></td>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>
<br/><br/>
<% if @carts.size > 0 %>
  <%= link_to 'Redirect Checkout', checkout_path, :confirm => "You are about to checkout. Continue?" %>
  <%= form_for(:checkout, :url => { :action => "request_charge" }) do |f| %>

  <div class="field">
    <%= f.label :account_alias %><br />
    <%= f.text_field :account_alias %>
  </div>
  <div class="actions">
    <%= f.submit "Onsite Payment" %>
  </div>
<% end %>
<% end %>

demo-store/app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

demo-store/app/views/carts/perform_charge.html.erb
<p id="notice"><%= @message %></p>
<h1>Payment Details</h1>
<p>Customer Name: <%= @customer_name %></p>
<p>Receipt Link: <%= link_to "download", @receipt_url %></p>
<p>Go Back: <%= link_to "Cart Page", root_url %></p>

demo-store/app/views/carts/request_charge.html.erb
<p id="notice"><%= notice %></p>
<h1>Enter Confirmation Token</h1>

  <%= form_for(:checkout, :url => { :action => "perform_charge" }) do |f| %>

  <div class="field">
    <%= f.label :confirm_token %><br />
    <%= f.text_field :confirm_token %>
    <%= f.hidden_field :opr_token, :value => @token %>
  </div>
  <div class="actions">
    <%= f.submit "Confirm Charge" %>
  </div>
<% end %>

demo-store/app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product name:</b>
  <%= @cart.product_name %>
</p>

<p>
  <b>Quantity:</b>
  <%= @cart.quantity %>
</p>

<p>
  <b>Price:</b>
  <%= @cart.price %>
</p>

<p>
  <b>Total Price:</b>
  <%= @cart.total_price %>
</p>


<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

demo-store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MpowerNew</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>